### ISSUE TITLE
Set collector group id on device group

### ISSUE THREAD

**Issue by xibriz** [ansible-collections/logicmonitor#18]
##### SUMMARY
It should be possible to set the collector group id on the device group. Autobalance should also be considered.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lm_device_group

##### ADDITIONAL INFORMATION
When creating or updating a device group, only collector id is possible to set.
Additional fields for collector group id and auto balance should be added.

```yaml
- name: Set Collector group id
  logicmonitor.integration.lm_device_group:
    action: update
    company: "..."
    access_id: "..."
    access_key: "..."
    full_path: "PATH/TO/GROUP"
    auto_balance: true
    collector_group_id: 1
    optype: replace
```
