### ISSUE TITLE
Enable Network Flow Analysis

### ISSUE THREAD

**Issue by xibriz** [ansible-collections/logicmonitor#21]
##### SUMMARY
Enable Network Flow Analysis on a given device

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
logicmonitor.integration.lm_device

##### ADDITIONAL INFORMATION
There should be attributes in the task to enable netflow on a given device then adding or updateing.

```yaml
- name: Update a device with netflow
    delegate_to: localhost
    logicmonitor.integration.lm_device:
      action: update
      enable_netflow: true
      netflow_collector_group_id: 1
      netflow_collector_id: 1
```
