### ISSUE TITLE
Enable LM Logs

### ISSUE THREAD

**Issue by xibriz** [ansible-collections/logicmonitor#22]
##### SUMMARY
There should be a way to enable LM logs

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
logicmonitor.integration.lm_device

##### ADDITIONAL INFORMATION
Enable or disable LM logs when adding or updateing a device.

```yaml
- name: Enable LM Logs
  delegate_to: localhost
  logicmonitor.integration.lm_device:
    action: update
    enable_log: true
    log_collector_group_id: 1
    log_collector_id: 1
```
