### ISSUE TITLE
Add link to an external resource

### ISSUE THREAD

**Issue by xibriz** [ansible-collections/logicmonitor#27]
##### SUMMARY
Add link to a lm_device

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
logicmonitor.integration.lm_device

##### ADDITIONAL INFORMATION
There should be attributes in the task to add a link to the device for external documentation when adding or updateing.

```yaml
- name: Update a device with link
    delegate_to: localhost
    logicmonitor.integration.lm_device:
      link: https://demo.netbox.dev/dcim/devices/1234/
```
