### ISSUE TITLE
Allow for dynamic groups

### ISSUE THREAD

**Issue by DII-dsward** [ansible-collections/logicmonitor#30]
##### SUMMARY
logicmonitor.integration.lm_device_group should allow for dynamic groups using applies_to

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
logicmonitor.integration.lm_device_group

##### ADDITIONAL INFORMATION
An 'applies_to' parameter could add a dynamic filter rule for auto-grouping devices

```yaml
# Example of adding a device group
- name: Add Device Group
  hosts: localhost
  tasks:
    - name: Create a Dynamic LogicMonitor Group for US-East Region
      logicmonitor.integration.lm_device_group:
        action: add
        company: "{{ logicmonitor_company }}"
        access_id: "{{ logicmonitor_access_id }}"
        access_key: "{{ logicmonitor_access_key }}"
        full_path: "DynamicGroups/US-East Devices"
        description: "Automatically groups all devices in the east region"
        applies_to: {
           auto.location =~ 'east'
        }
        disable_alerting: false

```
