### ISSUE TITLE
Create LM Users via play

### ISSUE THREAD

**Issue by henryjarend** [ansible-collections/logicmonitor#4]
##### SUMMARY
I'd like to create users (and API keys) via a playbook so I can fully automate my whole lifecycle of deploying LM at a client site

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lm_user

##### ADDITIONAL INFORMATION
This would ideally create a user and allow for full management of a LM tenant from purely one point of view. I'm trying to reduce the number of touch points and translation layers (ie using an API driven application and then copy pasting into another) so we can create a full end to end experience in Ansible
Below was all the vars I think we'd need. I might have missed one but should be everything that you can access via the API

```yaml
- name: Create LM User
  logicmonitor.integration.lm_user:
    action: add
    company: batman
    access_id: "temp admin id"
    access_key: "temp admin key"
    roles: [ dark_knight ]
    username: "bruce_wayne"
    email: "bruce@wayneenterprises.com"
```
