### ISSUE TITLE
lm_info target 'device' omit devices in sdt

### ISSUE THREAD

**Issue by JG127** [ansible-collections/logicmonitor#9]
##### SUMMARY
Devices in SDT (maintenance) are not listed in the output of module lm_info, target 'device'.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
module logicmonitor.integration.lm_info 

##### ANSIBLE VERSION

```paste below
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lm/PycharmProjects/lm_experiments/venv/lib/python3.10/site-packages/ansible
  executable location = /home/lm/PycharmProjects/lm_experiments/venv/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

##### COLLECTION VERSION

```paste below
Installing 'logicmonitor.integration:1.3.0'  (list option does not exist in this version of ansible-galaxy)
```

##### CONFIGURATION

```paste below
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/plugins/callback', '/home/****/.ansible/plugins/callback', '/usr/share/ansible/plugins/callback']
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/****']
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = ****
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/****
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
TAGS_SKIP(/etc/ansible/ansible.cfg) = ['*****']
```

##### OS / ENVIRONMENT

$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

##### STEPS TO REPRODUCE

Run a playbook with the two tasks specified below. No errors happen.

```yaml
    - name: Look up all devices
      lm_info:
        company: "{{ lm_company }}"
        access_id: "{{ lm_id }}"
        access_key: "{{ lm_key }}"
        target: device
      register: all_devices

    - name: "Dump info into /tmp/lm_devices.yml"
      copy:
        content: "{{ all_devices | to_nice_yaml }}"
        dest: /tmp/lm_devices.yml

```

##### EXPECTED RESULTS

A list of *all* devices, including those currently in SDT.

##### ACTUAL RESULTS

A list of devices, without those currently in SDT.
